### ISSUE TITLE
Error in run tstools gui

### ISSUE THREAD

**Issue by kashkoulimohammad** [MTgeophysics/mtpy#95]
Dear all,

I am trying to run tstools but I faced with this error:
```
(tstools) mkash@ubuntu:~/Downloads/mtpy-develop(1)/mtpy-develop/mtpy/gui/tstools$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from .tsscene import TSScene
ModuleNotFoundError: No module named '__main__.tsscene'; '__main__' is not a package
```
How can I solve this error?
Regards,
Mohammad

**Comment by kashkoulimohammad** [comment]
Even I tried on the Windows but I faced with the same error:
```
mamali@Lenovo-PC MINGW64 /c/mtpywin/mtpy/mtpy/gui/tstools (develop)
$ python example.py
Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from .tsscene import TSScene
ModuleNotFoundError: No module named '__main__.tsscene'; '__main__' is not a package
(tstools)
```
